version: '3.9'

services:
  djangoapp:
    container_name: recuperacao
    build:
      context: .
    ports:
      - 8000:8000
    volumes:
      - ./recuperacao:/recuperacao
      - ./data/web/static:/data/web/static/
      - ./data/web/media:/data/web/media/
    env_file:
      - ./dotenv_files/.env
    depends_on:
      - dbre
  dbre:
    container_name: dbre
    image: postgres:13-alpine
    ports:
      - "5435:5432"
    env_file:
      - ./dotenv_files/.env

volumes:
  postgres_data:
