# Generated by Django 4.2.8 on 2023-12-11 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cadastro_usuarios', '0004_usuario_uf_usuario_bairro_usuario_cep_usuario_cidade_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='UF',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='bairro',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='cep',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='cidade',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='complemento',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='cpf',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='email',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='endereco',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='idade',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='numero',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='rg',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='telefone',
        ),
        migrations.AddField(
            model_name='produto',
            name='marca',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='produto',
            name='ncm',
            field=models.CharField(max_length=8, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='produto',
            name='quantidade',
            field=models.IntegerField(null=True),
        ),
    ]
