# Generated by Django 4.2.7 on 2023-11-27 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produtos',
            fields=[
                ('id_produtos', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=20)),
                ('valor', models.CharField(max_length=10000)),
                ('quantidade', models.CharField(max_length=100000)),
                ('imagem', models.CharField(max_length=9)),
            ],
        ),
    ]
